### ISSUE TITLE
Memory requests

### ISSUE THREAD

**Issue by Sabryr** [bast/talk-better-resource-usage#1]
There are two main ways to ask for memory,  --mem-per-cpu and --mem.  --mem-per-cpu get multiplied by --ntasks. --mem is total memory allocated to all threads. I see that even --mem-per-cpu creates a memory pool, i.e. not all threads are supposed to use the equal amount of memory.  In that sense I found it less confusing to use --mem

**Comment by bast** [comment]
Thanks I will mention that and build it into the slides.
